### ISSUE TITLE
LTI PostGrade with Schoology

### ISSUE THREAD

**Issue by bapollack** [LtiLibrary/LtiLibrary#105]
I get the following call stack when I try to push grades to Schoology. I am using the same code to push grades to Canvas and that works fine. Also, a month ago the Schoology did work. Not sure how to debug this issue. I tried both the old obsolete LTILibrary as well as the latest LtiLibrary.Core. This is an Asp.Net project. 

The code is below:
            var ret = OutcomesClient.PostScore(outcomeServiceUrl, ClientID, ClientSecret, outcomeLisResultSourcedId, score / 100);

Call Stack:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at LtiLibrary.Core.Outcomes.v1.OutcomesClient.PostScore(String serviceUrl, String consumerKey, String consumerSecret, String lisResultSourcedId, Nullable`1 score)_

**Comment by wachulski** [comment]
```
at System.Net.Security.SslState.ForceAuthentication
```
Seems that your `outcomeServiceUrl` starts with `https://` and something got recently changed around SSL/TLS versions support or network configuration.

Compare your project's `System.Net.ServicePointManager.SecurityProtocol` against the outcome endpoint SSL/TLS version (if there is a match).

I bet it got changed to enforce TLS 1.2 and you need to explicitly set support for `System.Net.SecurityProtocolType.Tls12`

More here: https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5

**Comment by bapollack** [comment]
Thanks, that is what the issue was.

*Best Regards,*
*Brad Pollack*
*Chief Technology Officer*
*Castle Learning*
*(800) 345-7606 ext. 502*
*bpollack@castlelearning.com* <bpollack@castlelearning.com>
*Skype:bapollack*

**Comment by wachulski** [comment]
You welcome @bapollack 

Regards,
Marcin Wachulski
Integrations Team, itslearning AS
engineering.integration.team@itslearning.com
skype: marcinwachulski
