### ISSUE TITLE
Deadlock in OutcomesClient

### ISSUE THREAD

**Issue by andyfmiller** [LtiLibrary/LtiLibrary#31]
Got the latest source and built it. Then started testing the samples, starting with SimpleLti and Outcomes V1.

LtiLibrary.Core.Outcomes.v1.OutcomesClient.PostScore uses Core.Extensions.HttpExtensions.GetResponse to send the request to the SimpleLti.Controllers.OutcomesController and return the response.

The first problem I ran into is that OutcomesClient.CreateLtiOutcomesRequest was adding the wrong type of header. Easy fix.

The second problem I ran into is that HttpExtensions.GetResponse calls GetResponseAsync which then hangs. Some Googling lead me to believe the thread was deadlocked. So I made the entire call chain async (async SimpleLti.Controllers.ProviderController.Outcomes1 and async OutcomesClient.PostScore) and changed PostScore to await GetResponseAsync directly.

GetResponseAsync no longer hangs (which makes me think it was deadlocked). But now it throws an exception "Error while copying content to a stream."

The inner exception is
`
Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.get_Position()
   at System.Net.Http.StreamToStreamCopy.StartAsync()
`

I have not been able to figure this out. [This issue](https://github.com/dotnet/corefx/issues/8113) in dotnet / corefx makes me wonder if this is a bug in .NET.

Anyone have any ideas?

**Comment by andyfmiller** [comment]
I figured it out. The closed stream was the webRequest.Content stream which is created by OutcomesClient.CreateLtiOutcomesRequest. I simply removed the "using" and now it works.
